modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="create_pop_playthings"
version="${file.jarVersion}"
displayName="Create: Pop Playthings"
authors="Jimii"
description='''Interactive Create-crafted toys and activities for Just Create SMP Pops.'''
[[mixins]]
config="create_pop_playthings.mixins.json"

[[dependencies.create_pop_playthings]]
modId="neoforge"
type="required"
versionRange="[21.1.233,21.2)"
ordering="NONE"
side="BOTH"

[[dependencies.create_pop_playthings]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.21.2)"
ordering="NONE"
side="BOTH"

[[dependencies.create_pop_playthings]]
modId="create"
type="required"
versionRange="[6.0.10,6.0.11)"
ordering="AFTER"
side="BOTH"

[[dependencies.create_pop_playthings]]
modId="jcsmp_pops"
type="required"
versionRange="[1.0.2,1.0.3)"
ordering="AFTER"
side="BOTH"
